### ISSUE TITLE
install.sh fails

### ISSUE THREAD

**Issue by Frituurpanda** [dtag-dev-sec/t-pot-autoinstall#46]
Hi, running the auto-install script on Ubuntu 16.04 LTS fails at installing docker-compose:

```
### Installing docker-compose.
Requirement already satisfied: docker-compose==1.16.1 in /usr/local/lib/python2.7/dist-packages (1.16.1)
Requirement already satisfied: websocket-client<1.0,>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (0.48.0)
Requirement already satisfied: requests!=2.11.0,<2.12,>=2.6.1 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (2.11.1)
Requirement already satisfied: PyYAML<4,>=3.10 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (3.13)
Requirement already satisfied: dockerpty<0.5,>=0.4.1 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (0.4.1)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (1.0.22)
Requirement already satisfied: docopt<0.7,>=0.6.1 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (0.6.2)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (3.5.0.1)
Requirement already satisfied: enum34<2,>=1.0.4; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (1.1.6)
Requirement already satisfied: texttable<0.10,>=0.9.0 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (0.9.1)
Requirement already satisfied: cached-property<2,>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (1.4.3)
Requirement already satisfied: docker<3.0,>=2.5.1 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (2.7.0)
Requirement already satisfied: jsonschema<3,>=2.5.1 in /usr/local/lib/python2.7/dist-packages (from docker-compose==1.16.1) (2.6.0)
Requirement already satisfied: six<2,>=1.3.0 in /usr/lib/python2.7/dist-packages (from docker-compose==1.16.1) (1.11.0)
Requirement already satisfied: docker-pycreds>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from docker<3.0,>=2.5.1->docker-compose==1.16.1) (0.3.0)
Requirement already satisfied: functools32; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from jsonschema<3,>=2.5.1->docker-compose==1.16.1) (3.2.3.post2)
apscheduler 3.5.1 requires pytz, which is not installed.
tzlocal 1.5.1 requires pytz, which is not installed.
docker 2.7.0 has requirement requests!=2.18.0,>=2.14.2, but you'll have requests 2.11.1 which is incompatible.
### Installing elasticsearch curator.
Requirement already satisfied: elasticsearch-curator==5.2.0 in /usr/local/lib/python2.7/dist-packages (5.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator==5.2.0) (2018.4.16)
Requirement already satisfied: elasticsearch<6.0.0,>=5.4.0 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator==5.2.0) (5.5.3)
Requirement already satisfied: pyyaml>=3.10 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator==5.2.0) (3.13)
Requirement already satisfied: voluptuous>=0.9.3 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator==5.2.0) (0.11.1)
Requirement already satisfied: click>=6.7 in /usr/local/lib/python2.7/dist-packages (from elasticsearch-curator==5.2.0) (6.7)
Requirement already satisfied: urllib3>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from elasticsearch<6.0.0,>=5.4.0->elasticsearch-curator==5.2.0) (1.23)
apscheduler 3.5.1 requires pytz, which is not installed.
tzlocal 1.5.1 requires pytz, which is not installed.
docker 2.7.0 has requirement requests!=2.18.0,>=2.14.2, but you'll have requests 2.11.1 which is incompatible.
### Installing wetty.
/usr/local/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
server#
```

Thoughts?

**Comment by t3chn0m4g3** [comment]
For some reason it will not install `pytz` as a dep. Try `pip install pytz`.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved. Closing for now.
